---
- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade ALL apt package
  ansible.builtin.apt:
    upgrade: dist

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  ansible.builtin.stat:
    path: /var/run/reboot-required

- name: Reboot the Debian or Ubuntu server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 300
    test_command: uptime
  when: reboot_required_file.stat.exists
