apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: traefik
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 34.4.1
    helm:
      releaseName: traefik
      valuesObject:
        ingressClass:
          enabled: true
          isDefaultClass: true
        ingressRoute:
          dashboard:
            enabled: false
        logs:
          general:
            level: INFO
        persistence:
          accessMode: ReadWriteOnce
          enabled: true
          name: ssl-certs
          path: /ssl-certs
          size: 1Gi
        ports:
          web: null
          websecure:
            tls:
              enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
