apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: traefik
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 35.2.0
    helm:
      releaseName: traefik
      valuesObject:
        deployment:
          kind: DaemonSet  # Run Traefik on every node for high availability
        service:
          spec:
            type: LoadBalancer
            externalTrafficPolicy: Local
        ports:
          web:
            redirectTo:
              port: websecure  # Redirect HTTP to HTTPS
          websecure:
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: true
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        persistence:
          enabled: true
          size: 1Gi
          accessMode: ReadWriteOnce
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
