apiVersion: apps.gitlab.com/v1beta2
kind: Runner
metadata:
  name: gitlab-instance-runner
spec:
  gitlabUrl: 'https://git.server.dortlii.dev'
  imagePullPolicy: Always
  tags: 'k3s-runner'
  token: gitlab-runner-secret