apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: vaultwarden
  sources:
    - chart: vaultwarden
      repoURL: https://guerzon.github.io/vaultwarden
      targetRevision: 0.31.8
      helm:
        valuesObject:
          domain: "https://vw.dortlii.dev"
          signupsAllowed: false
          invitationsAllowed: false
          adminToken:
            existingSecret: admin-token
            existingSecretKey: token
          timeZone: "Europe/Zurich"
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
        releaseName: vaultwarden
    - repoURL: 'https://git.server.dortlii.dev/api/v4/projects/6/packages/helm/stable'
      targetRevision: 0.0.4
      chart: traefik-ingress
      helm:
        releaseName: vaultwarden-ingress
        valuesObject:
          global:
            namespace: vaultwarden
          cert:
            enabled: true
            name: vaultwarden-cert
            secretName: vaultwarden-tls-secret
            dnsNames: vw.dortlii.dev
          issuerRef:
            name: acme-issuer
            kind: ClusterIssuer
          ingress:
            enabled: true
            name: vaultwarden-ingress
            path: /
            pathType: Prefix
            backend:
              port: 80
              service: vaultwarden
            serversTransports:
              ignorecert:
                insecureSkipVerify: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
