apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  project: awx
  source:
    chart: awx-operator
    repoURL: https://ansible-community.github.io/awx-operator-helm/
    targetRevision: 2.19.1
    helm:
      releaseName: awx-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
