- name: prepare server
  hosts: nextcloud
  become: true
  vars_files:
    - vars/nextcloud_vars.yml
  pre_tasks:
  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    # changed_when: false
    when: ansible_distribution == "Ubuntu"

- name: install nextcloud  
  roles:
    - { role: nextcloud } 