---
- name: Install qemu guest agent
  ansible.builtin.yum:
        name: qemu-guest-agent
        state: present

- name: Enable and start qemu guest agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: yes
    state: started
