apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-cert
  namespace: portainer
spec:
  dnsNames:
  - portainer.apps.prd-1.k8s.dortlii.dev
  issuerRef:
    kind: ClusterIssuer
    name: acme-issuer
  secretName: portainer-tls-secret