apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer-helm
  namespace: argocd
spec:
  project: portainer
  source:
    chart: portainer
    repoURL: https://portainer.github.io/k8s/
    targetRevision: 1.0.52
    helm:
      releaseName: portainer
      valuesObject:
        enterpriseEdition:
          enabled: true
        service:
          type: ClusterIP
        tls:
          force: false
        ingress:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
    - CreateNamespace=true
